"use client";
import localFont from "next/font/local";
import "./globals.css";
import { LoadingProvider, useLoading } from "./Contexts/loading";
import { ClipLoader } from "react-spinners";
import Header from "./Components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Study Hug",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LoadingProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <GlobalSpinner />
        {children}
       </body>
      </html>
    </LoadingProvider>
  );
}
const GlobalSpinner = () => {
  const { isLoading } = useLoading();

  return (
    isLoading && (
      <div className="fixed w-full h-full flex justify-center bg-[#D0D5DD] items-center z-20 opacity-75">
        <ClipLoader color="#2A80FF" size={60} />
      </div>
    )
  );
};
